language: python
python:
  - "2.7"
  - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
  - "pypy3"
# command to install dependencies
install:
  - pip install green
  - pip install coverage
  - pip install coveralls
  - pip install .
# command to run tests
script: green -r -v -s 8 -o '*lib/python*/*,*site-package*,*tests*.py,*pypy*'
after_success: coveralls
